version: "3"

services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    networks:
      - bridgeNetwork
    ports:
      - '9092:9092'
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  schema-registry:
    image: bitnami/schema-registry:latest
    container_name: schema-registry
    hostname: schema-registry
    networks:
      - bridgeNetwork
    ports:
      - '8081:8081'
    volumes:
      - registry_data:/bitnami
    environment:
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_DEBUG=true

  hnt-app:
    build: ./
    container_name: hnt-app
    networks:
      - bridgeNetwork
    depends_on:
      - kafka
      - schema-registry

volumes:
  kafka_data:
    driver: local
  registry_data:
    driver: local
networks:
  bridgeNetwork:
    driver: "bridge"


