spring:
  application:
    name: spring-kafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-1

server:
  port: 9191