spring:
  application:
    name: spring-kafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        schema.registry.url: http://localhost:8081
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific:
          avro:
            reader: "true"
        spring:
          json:
            trusted:
              packages: "*"


server:
  port: 9191